version: '3.7'

services:
  warehouse:
    build: ./warehouse
    #image: docker.io/springarchitect/warehouse:latest
    labels:
      filebeat_enable:
    networks:
      - exceptionhandling
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=json"

  order:
    build: ./order
    #image: docker.io/springarchitect/warehouse:latest
    labels:
      filebeat_enable:
    networks:
      - exceptionhandling
    ports:
      - "8082:8080"
    expose:
      - "8082"
    environment:
      - "warehouse.url=host.docker.internal:8080"
      - "spring.profiles.active=json"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    networks:
      - exceptionhandling
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /tmp/data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    networks:
      - exceptionhandling
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  logstash:
    build: ./elk/logstash
    networks:
      - exceptionhandling
    command: logstash -f /conf/logstash-spring-boot.conf
    ports:
      - "5044:5044"
    links:
      - elasticsearch

  filebeat:
    build: ./elk/filebeat
    networks:
      - exceptionhandling
    volumes:
      # needed to access all docker logs :
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      # needed to access additional information about containers
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  exceptionhandling:
    driver: "bridge"