spring:
  application:
    name: warehouse
  output:
    ansi:
      enabled: always
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
logging:
  level:
    de.fabiankrueger: TRACE
